version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis-data:/data

  movie-service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    container_name: movie-service
    ports:
      - "8083:8083"
      - "50053:50053"
    env_file:
      - ./movie-service/.env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8005:8005"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

    # notification-service:
    # build:
    #   context: ./notification-service
    #   dockerfile: Dockerfile
    # container_name: notification-service
    # environment:
    #   - DB_HOST=postgres
    #   - DB_PORT=5432
    #   - DB_USER=cinema_user
    #   - DB_PASSWORD=cinema_password
    #   - DB_NAME=cinema_db
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_PASSWORD=
    # ports:
    #   - "8082:8080"
    # depends_on:
    #   postgres:
    #   redis:

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8082:8082"
    env_file:
      - ./booking-service/.env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - movie-service
      - auth-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:3000
      - USER_SERVICE_URL=http://user-service:3001
      - MOVIE_SERVICE_URL=http://movie-service:8083
      - BOOKING_SERVICE_URL=http://booking-service:8082
      - NOTIFICATION_SERVICE_URL=http://notification-service:8080
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - movie-service
      - booking-service
      - redis
  
  # worker-service:
  #   build:
  #     context: ./worker-service
  #     dockerfile: Dockerfile
  #   container_name: worker-service
  #   depends_on:
  #     postgres:
  #     redis:

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./FE/.env
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api-gateway

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: cinema-network
